const aboutMe = 
{
    utsa: "My story of becoming a software developer starts from humble beginnings. As a young adult, my education and necessities were not afforded to me by loving parents, but earned by working in a restaurant 30-40 hours a week. I attended the University of Texas at San Antonio for Public Health Administration, which at the time had a 26% graduation rate. I felt the sting of this statistic throughout my 4 years of attendance: the classes I needed to graduate always unavailable, the teachers too busy to give attention to personal growth, and a focus on sports and university status sans the graduation of attending students. I wasn’t well equipped to handle a system that wasn’t readily navigable either. With no guidance from my family, who were constantly in conflict with each other, and little help from counselors overwhelmed with thousands of students with similar problems, I was too busy surviving to keep up. I was forced to end my journey at UTSA, when the loans I needed to pay for college could not be acquired, because the number of hours I was taking was too low due to the fact that none of the classes I needed to graduate were available to take. An impossible cycle.",
    
    carpentry:"Defeated, and in debt I decided to try and learn a trade. Maybe college wasn’t the answer. My nuclear family was in too much turmoil and I knew I needed time away from them to work effectively. Thankfully, I had support from my grandfather, a carpenter of 50 years and an established businessman in the city of Tyler, Texas. At 22 I moved there from San Antonio, and worked for 3 years as an apprentice framer. I credit this experience as one of my most valuable, because the practical skills I gained form the foundation of how I solve problems today. Still, I yearned for a more intellectually stimulating career, and enjoyed programming as a hobby with some of my close friends. These same friends informed me of a free software development program called 42 in Silicon Valley. However, money again stood in the way. The program was intense, requiring applicants to pass a month long exam called a piscine of which only 30% were accepted . On top of this, to remain in the free housing they provide, students must maintain 38 hours of work in software development, pass weekly rigorous exams, and complete a minimum number of projects per month. I knew there was no way to accomplish without something to live on while I developed my skills. My friends went on to attend the program, while I devised a plan of action to follow.",

    oilField: "Through another friend I landed a job in Oilfield Solids Control at a company that would allow me to work overtime beyond the OSHA safety restrictions. Dangerous work environments, 36 hour shifts without sleep, and driving thousands of miles throughout 5 week hitches were just a few of the challenges I overcame. Even though my job consumed most of my life, on my single week off between hitches, I would practice coding for the month long entrance exam at 42 called “the piscine”, meaning swimming pool in French. The company often had to switch me to different locations so that their hiring producers wouldn’t notice how many continuous 12-hour shifts I worked and call a safety officer. However, the fact that I worked so many days was quickly noticed by the company field managers. To get the most value out of me, the company quickly trained me to maintain, repair, and set up every single piece of solids control equipment they owned. Big bowl centrifuges, shale shakers, class-3 and class-7 forklifts, earthmovers, and diesel pressure washers where just some of the machinery I had the opportunity to learn. As a tech, I never had to call in equipment to our shop mechanic when deployed out on a rig because I could fix the machines with tools and components laying around, and not have to incur the shipping and pick up costs. Within 9 months, I had saved enough to live on for a year and bought a newer car to drive to California. The experience here, of learning to use what’s already present, and how with enough creativity anything can fit together to work correctly has proved valuable to me as a programmer today.",
    
    fortyTwo: "The Piscine consisted of small projects that become available at 8:42am each day and end at 11:42pm the following day. Students start off doing simple projects like creating bash scripts that demonstrate mastery of basic unix cli commands. As the piscine continues, projects move to developing programs and utilities in the C language. Everything is submitted to the school’s private git repository under your profile name, and graded by an automated system called “Moulinette”. A single mistake, and your project instantly receives a grade of zero. During this experience, my preparation and acclamation to hard work paid off.  I was accepted as a student at 42, acquired a spot in the dorms, and set to work researching relevant skills and technologies that would allow me to work as a professional software developer as soon as possible. Since front end technologies were easier to learn I quickly picked up React, Redux, and RxJs and was able to start contracting for RDT Dev as a front end developer. I used what I learned as a carpenter, listening to and emulating the experienced developers at RDT to increase effectiveness and productivity quickly. This month I shipped a software system that allows greater management and control of our customer’s enterprise index repositories in Splunk."
}

export default aboutMe